defmodule DeutchLernen.Repo.Migrations.CreateWordInstances do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:word_instances, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position_in_sentence, :bigint, null: false
      add :inflected_form, :text
      add :case_usage, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :word_id,
          references(:words,
            column: :id,
            name: "word_instances_word_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :sentence_id,
          references(:sentences,
            column: :id,
            name: "word_instances_sentence_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:word_instances, "word_instances_word_id_fkey")

    drop constraint(:word_instances, "word_instances_sentence_id_fkey")

    drop table(:word_instances)
  end
end
