defmodule DeutchLernen.Repo.Migrations.CreateWords do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:words, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :lemma, :text, null: false
      add :article, :text
      add :word_type, :text, null: false, default: "nomen"
      add :gender, :text
      add :plural_form, :text
      add :verb_type, :text
      add :separable_prefix, :text
      add :level, :text, null: false, default: "b1"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:words, [:lemma], name: "words_unique_lemma_index")
  end

  def down do
    drop_if_exists unique_index(:words, [:lemma], name: "words_unique_lemma_index")

    drop table(:words)
  end
end
